exclude: |
  (?x)
  # NOT INSTALLABLE ADDONS
  ^base_url/|
  ^partner_contact_company/|
  ^product_online_category/|
  ^shopinvader/|
  ^shopinvader_algolia/|
  ^shopinvader_assortment/|
  ^shopinvader_auth_api_key/|
  ^shopinvader_auth_jwt/|
  ^shopinvader_backend_image_proxy/|
  ^shopinvader_cart_expiry/|
  ^shopinvader_category_image_for_product/|
  ^shopinvader_contact_address_default/|
  ^shopinvader_contact_company/|
  ^shopinvader_customer_activity/|
  ^shopinvader_customer_invoicing_mode/|
  ^shopinvader_customer_multi_user/|
  ^shopinvader_customer_multi_user_company_group/|
  ^shopinvader_customer_multi_user_validate/|
  ^shopinvader_customer_multi_user_wishlist/|
  ^shopinvader_customer_price/|
  ^shopinvader_customer_price_wishlist/|
  ^shopinvader_customer_validate/|
  ^shopinvader_delivery_carrier/|
  ^shopinvader_delivery_instruction/|
  ^shopinvader_delivery_state/|
  ^shopinvader_demo_app/|
  ^shopinvader_easy_binding/|
  ^shopinvader_elasticsearch/|
  ^shopinvader_guest_mode/|
  ^shopinvader_image/|
  ^shopinvader_import_image/|
  ^shopinvader_invoice/|
  ^shopinvader_lead/|
  ^shopinvader_locomotive/|
  ^shopinvader_locomotive_algolia/|
  ^shopinvader_locomotive_contact_company/|
  ^shopinvader_locomotive_elasticsearch/|
  ^shopinvader_locomotive_guest_mode/|
  ^shopinvader_locomotive_reset_password/|
  ^shopinvader_locomotive_sale_profile/|
  ^shopinvader_locomotive_wishlist/|
  ^shopinvader_membership/|
  ^shopinvader_multi_cart/|
  ^shopinvader_multi_category/|
  ^shopinvader_notification_default/|
  ^shopinvader_partner_firstname/|
  ^shopinvader_partner_vat/|
  ^shopinvader_pending_cart_reminder/|
  ^shopinvader_portal_mode/|
  ^shopinvader_pos/|
  ^shopinvader_price_per_qty/|
  ^shopinvader_product_attribute_set/|
  ^shopinvader_product_brand/|
  ^shopinvader_product_brand_image/|
  ^shopinvader_product_brand_tag/|
  ^shopinvader_product_manufactured_for/|
  ^shopinvader_product_media/|
  ^shopinvader_product_new/|
  ^shopinvader_product_order/|
  ^shopinvader_product_price_tax/|
  ^shopinvader_product_stock/|
  ^shopinvader_product_stock_assortment/|
  ^shopinvader_product_stock_forecast/|
  ^shopinvader_product_stock_forecast_expiry/|
  ^shopinvader_product_stock_state/|
  ^shopinvader_product_template_multi_link/|
  ^shopinvader_product_template_multi_link_date_span/|
  ^shopinvader_product_template_tags/|
  ^shopinvader_product_variant_multi_link/|
  ^shopinvader_product_variant_selector/|
  ^shopinvader_product_video_link/|
  ^shopinvader_promotion_rule/|
  ^shopinvader_quotation/|
  ^shopinvader_sale_amount_by_group/|
  ^shopinvader_sale_automatic_workflow/|
  ^shopinvader_sale_communication/|
  ^shopinvader_sale_coupon/|
  ^shopinvader_sale_packaging/|
  ^shopinvader_sale_packaging_wishlist/|
  ^shopinvader_sale_profile/|
  ^shopinvader_sale_report/|
  ^shopinvader_wishlist/|
  # END NOT INSTALLABLE ADDONS
  # Files and folders generated by bots, to avoid loops
  ^setup/|/static/description/index\.html$|
  # We don't want to mess with tool-generated files
  .svg$|/tests/([^/]+/)?cassettes/|^.copier-answers.yml$|^.github/|
  # Maybe reactivate this when all README files include prettier ignore tags?
  ^README\.md$|
  # Library files can have extraneous formatting (even minimized)
  /static/(src/)?lib/|
  # Repos using Sphinx to generate docs don't need prettying
  ^docs/_templates/.*\.html$|
  # You don't usually want a bot to modify your legal texts
  (LICENSE.*|COPYING.*)
default_language_version:
  python: python3
  node: "16.17.0"
repos:
  - repo: local
    hooks:
      # These files are most likely copier diff rejection junks; if found,
      # review them manually, fix the problem (if needed) and remove them
      - id: forbidden-files
        name: forbidden files
        entry: found forbidden files; remove them
        language: fail
        files: "\\.rej$"
      - id: en-po-files
        name: en.po files cannot exist
        entry: found a en.po file
        language: fail
        files: '[a-zA-Z0-9_]*/i18n/en\.po$'
  - repo: https://github.com/oca/maintainer-tools
    rev: 4cd2b852214dead80822e93e6749b16f2785b2fe
    hooks:
      # update the NOT INSTALLABLE ADDONS section above
      - id: oca-update-pre-commit-excluded-addons
      - id: oca-fix-manifest-website
        args: ["https://github.com/shopinvader/odoo-shopinvader"]
  - repo: https://github.com/myint/autoflake
    rev: v1.6.1
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: prettier (with plugin-xml)
        additional_dependencies:
          - "prettier@2.7.1"
          - "@prettier/plugin-xml@2.2.0"
        args:
          - --plugin=@prettier/plugin-xml
        files: \.(css|htm|html|js|json|jsx|less|md|scss|toml|ts|xml|yaml|yml)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.2
    hooks:
      - id: pyupgrade
        args: ["--keep-percent-format"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort except __init__.py
        args:
          - --settings=.
        exclude: /__init__\.py$
  - repo: https://github.com/acsone/setuptools-odoo
    rev: 3.1.8
    hooks:
      - id: setuptools-odoo-make-default
      - id: setuptools-odoo-get-requirements
        args:
          - --output
          - requirements.txt
          - --header
          - "# generated from manifests external_dependencies"
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies: ["flake8-bugbear==21.9.2"]
  - repo: https://github.com/OCA/pylint-odoo
    rev: 7.0.2
    hooks:
      - id: pylint_odoo
        name: pylint with optional checks
        args:
          - --rcfile=.pylintrc
          - --exit-zero
        verbose: true
      - id: pylint_odoo
        args:
          - --rcfile=.pylintrc-mandatory
